### ISSUE TITLE
Using Carlos to cache videos

### ISSUE THREAD

**Issue by blurtime** [WeltN24/Carlos#172] opened 2017-06-13 15:50 UTC
Is there a way to play cached videos (which initially came from a server) using AVPlayer or plugins like https://github.com/piemonte/Player (similar to the way one can display cached images: `.onSuccess { value in` and then next line: `UIImageView(image: value)`) or does one have to find out where exactly the (video) file is stored in order to provide the URL and play it?

**Comment by vittoriom** [comment] 2017-06-14 16:58
Hi @blurtime 
I think it depends on your use case, especially on which video player you're using. 
There are no ways to cache videos and play them out of the box at the moment, but if your video player supports opening videos through a path to a file on the disk, you might want to download them first and then build a cache level that given an object returns the path where the video associated to it is stored if present, or fails otherwise. Then you can use the syntax you mentioned above.

**Comment by blurtime** [comment] 2017-06-14 17:29
First of all, thank you for answering @vittoriom!
I've tried to somehow get the local URL of the file yesterday but couldn't find anything (i.a. on stackoverflow). So I was wondering if you could help me and show me how you would retrieve the URL of the downloaded video (on the device)? I would really appreciate your help!

**Comment by vittoriom** [comment] 2017-06-14 17:52
On a very high level, I would create a custom `Fetcher` similar to `NetworkFetcher` but saving the content of the URLs to disk and simply returning the path where the content was saved. 

This could be easily chained with a `DiskCacheLevel` and a `MemoryCacheLevel` to create a `BasicCacheLevel<URL, URL>`. The idea is that the input for the resulting cache is a `URL` (but could also be a domain object that contains the URL, so that you can save the files on disk using more information than just the URL - in this code example we're hashing the URL itself) and the output is the path where the video file is stored. If no path is found, it means that the video was never downloaded and the `Fetcher` will download it and save it to disk.

The fetcher `get` would do something like this (the code is mostly copied from [this](http://swiftdeveloperblog.com/code-examples/download-file-from-a-remote-url-in-swift/) link:

```swift
// Create destination URL 
let result = new Promise<URL>()
let documentsUrl: URL =  FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first as URL!
let destinationFileUrl = documentsUrl.appendingPathComponent(key.md5())
    
//Create URL to the source file you want to download 
let sessionConfig = URLSessionConfiguration.default
let session = URLSession(configuration: sessionConfig)
 
let request = URLRequest(url: key)
    
let task = session.downloadTask(with: request) { (tempLocalUrl, response, error) in
    if let tempLocalUrl = tempLocalUrl, error == nil {
        // Success
        do {
            try FileManager.default.copyItem(at: tempLocalUrl, to: destinationFileUrl)
            result.succeed(destinationFileUrl)
        } catch (let writeError) {
            print("Error creating a file \(destinationFileUrl) : \(writeError)")
            result.fail(writeError)
        }
            
    } else {
        print("Error took place while downloading a file. Error description: %@", error?.localizedDescription);
        result.fail(error)
    }
}
task.resume()

return result
```

For the `md5` implementation you could use a gist like [this](https://gist.github.com/khanlou/baf60dd62601b879eeba209943b04973).

Please take this code with a grain of salt since I didn't write it in any IDE. Moreover, you should rather use an existing component that downloads files from the network rather than writing your own. 

Please let me know if this looks clear for you.

**Comment by blurtime** [comment] 2017-06-14 18:21
I understand your approach. Nevertheless, I am wondering if there is a simpler way. In order to show you what I mean I am going to provide a simplified example from my code: 

    let omniCache = videoCache.cache
    let request = omniCache.get(URL(string: video!)!)
        
    request
    .onSuccess { videoFile in
                
        //here I would like to enter the local url, of course this would result in an error currently since I would be entering NSData...
        if let videoURL = URL(fileURLWithPath: videoFile){

            //use videoURL to e.g. create an AVPlayerItem like: AVPlayerItem(url: videoURL as URL)

So my question is if one can retrieve the local URL even in the request.onSuccess provided by Carlos. I found this (https://stackoverflow.com/questions/28419188/how-can-i-retrieve-local-files-with-nsurl) on stackoverflow and was wondering if there is a way to retrieve the local url with the file so to say.

**Comment by vittoriom** [comment] 2017-06-14 20:56
As of now, there is no way you can use the out-of-the-box `CacheLevel`s to achieve what you want. The only level interacting with the network is the `NetworkFetcher` and it only deals with `Data`, it doesn't store the files on disk. 

The reason why Carlos was built in a modular fashion is exactly because it's not meant to cover all use cases. It's quite easy to create your own `Fetcher` or `CacheLevel`, the code above should basically be all it takes to create the `Fetcher` you need and compose it with the memory and disk levels. 

The other way that comes to my mind is to use `conditionedValueTransformation ` on the `NetworkFetcher` to actually store the `Data` on disk using the `URL` as the file name (or its hash) and return the path you saved the video to. 
Then, composed with the `DiskCacheLevel` and the `MemoryCacheLevel`, the result will be a `BasicCache<URL, URL>` which is what you want.

The only code needed for this should be the transformer that saves the data on disk and returns the file URL.

**Comment by vittoriom** [comment] 2017-06-14 20:59
The question you posted shows a hacky way of leveraging knowledge of how Haneke stores files on disk to work around a similar limitation that you encountered with Carlos. 

Of course looking at the implementation of the `DiskCacheLevel` you could come up with similar code that reads the file previously saved on disk, I would not recommend going this way since it leaks abstractions.

**Comment by blurtime** [comment] 2017-06-15 07:21
I understand, thank you for the explanation! Really appreciate it! 

I've tried to create a custom fetcher now (without md5 for the moment, had to change the code you had shown me a little (s. comments)) but I am still getting a few errors.

Here is my `class CustomFetcher: Fetcher`:

    typealias KeyType = URL
    typealias OutputType = URL
    
    func get(_ key: KeyType) -> Future<OutputType> {
        
        // Create destination URL
        let result = Promise<URL>() //before: new Promise<URL>()
        let documentsUrl: URL =  FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first as URL!
        let destinationFileUrl = documentsUrl.appendingPathComponent(key.absoluteString) //absolute String othersince String is expected argument
        
        //Create URL to the source file you want to download
        let sessionConfig = URLSessionConfiguration.default
        let session = URLSession(configuration: sessionConfig)
        
        let request = URLRequest(url: key)
        
        let task = session.downloadTask(with: request) { (tempLocalUrl, response, error) in
            if let tempLocalUrl = tempLocalUrl, error == nil {
                // Success
                do {
                    try FileManager.default.copyItem(at: tempLocalUrl, to: destinationFileUrl)
                    result.succeed(destinationFileUrl)
                } catch (let writeError) {
                    print("Error creating a file \(destinationFileUrl) : \(writeError)")
                    result.fail(writeError)
                }
                
            } else {
                print("Error took place while downloading a file. Error description: %@", error?.localizedDescription ?? String()); //default type was needed
                result.fail(error!) //! to force-unwrap
            }
        }
        
        task.resume()
        
        return result
        
    }

The error I get in this class is `Cannot convert return expression of type 'Promise<URL>' to return type 'Future<CustomFetcher.OutputType>' (aka 'Future<URL>')`. If I change `let result = Promise<URL>()` to `let result = Future<URL>()`, it tells me it `cannot invoke initializer for Future<URL>with no arguments. And if I change `func get(_ key: KeyType) -> Future<OutputType>` to `func get(_ key: KeyType) -> Promise<OutputType>`, it tells me `Type 'CustomFetcher' does not conform to protocol 'CacheLevel'` which makes sense since a Future is expected... 

The second error I get happens when I want to compose the CustomFetcher with memory and disk cache levels. It always wants me to define some types but <URL, URL> doesn't work which makes sense as well since it wouldn't conform.

`public struct videoCache`:

    //create cache for videos
    static let cache = MemoryCacheLevel()
        compose(DiskCacheLevel<<#K: StringConvertible#>, NSCoding>()) //before: .compose(DiskCacheLevel())
        .compose(CustomFetcher())

Last but not least an important question: 

Will the videos not stay stored on the disk until they are somehow deleted? I tried a slightly modified function from the one in this [link](http://swiftdeveloperblog.com/code-examples/download-file-from-a-remote-url-in-swift/) you provided without the compositions (and just used it instead of my `get` I had until then) and the videos appeared to have been stored without ever being deleted (if the same link was requested more than once one would get an error telling one that a file with the same name already existed there). Do I need to write another function to somehow remove them at some point since I actually only want to cache...?

**Comment by vittoriom** [comment] 2017-06-15 07:32
Hi,

the first error is easy to fix: keep creating a `Promise<URL>`, just return `result.future` in the last line.

For the second error, I believe `URL` should conform to `NSCoding`. If not, you can extend it to do so. Then you should be able to compose `MemoryCacheLevel` with `DiskCacheLevel` and `CustomFetcher`. Maybe try to help the compiler by explicitly saying that the `static let cache` is of type `BasicCache<URL, URL>`. 

As for the last question: the videos will stay on disk until the disk space reaches the threshold specified in the `DiskCacheLevel` initializer. You can tweak that to be how many MB/GB you'd like.

**Comment by blurtime** [comment] 2017-06-15 08:15
The first error disappeared, sorry for that stupid question in retrospect...

The second error still isn't that clear to me, URL does not conform and I am not sure how to extend it to conform to URL. I am still learning swift... And if I try to help the compiler, by adding type `BasicCache<URL, URL>`, it tells me to do this: `MemoryCacheLevel<<#K: StringConvertible#>, <#T: ExpensiveObject & AnyObject#>>()` if I leave `DiskCacheLevel` like that: `.compose(DiskCacheLevel())` and still the same error I had with conformation (initial error) if it looks like that: `.compose(DiskCacheLevel<URL, URL>())`.  

How do I initialize? Do I need to create an `init` for DiskCacheLevel?

**Comment by vittoriom** [comment] 2017-06-15 16:19
I see, maybe the issue is that `URL` is not `AnyObject`? In that case, you might need to use `NSURL` or just store the String version of the `URL` instead as the value of the cache.

`DiskCacheLevel` already comes with an [initializer](https://github.com/WeltN24/Carlos/blob/master/Carlos/DiskCacheLevel.swift#L45). You just need to specify which `capacity` you want

**Comment by blurtime** [comment] 2017-06-15 16:28
I already feared you would say that and changed my code and it looks like this now:

    static let cache: BasicCache<URL, NSURL> = MemoryCacheLevel()
        .compose(DiskCacheLevel<URL, NSURL>()) //error occurs
        .compose(CustomFetcher())

Unfortunately, I get an error now which I cannot explain, namely: `Type of expression is ambiguous without more context`. Do you have any idea what to do here?

Perfect! Just thought for a moment because it sounded like I needed to call it again...

**Comment by vittoriom** [comment] 2017-06-15 16:31
Not sure this is the issue or if you already addressed it, but did you change the `OutputType` of your `CustomFetcher` to `NSURL` to make sure that all the types match?

**Comment by blurtime** [comment] 2017-06-15 16:44
I did the same thing today, too and still get the same error (also changed the Promise to NSURL and had to add a little bit of code as suggested by Xcode at `result.succeed`):

    typealias KeyType = URL
    typealias OutputType = NSURL
    
    func get(_ key: KeyType) -> Future<OutputType> {
        
        // Create destination URL
        let result = Promise<NSURL>() //before: Promise<URL>() - now NSURL
        let documentsUrl: URL =  FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first as URL!
        let destinationFileUrl = documentsUrl.appendingPathComponent(key.absoluteString) 
        
        //Create URL to the source file you want to download
        let sessionConfig = URLSessionConfiguration.default
        let session = URLSession(configuration: sessionConfig)
        
        let request = URLRequest(url: key)
        
        let task = session.downloadTask(with: request) { (tempLocalUrl, response, error) in
            if let tempLocalUrl = tempLocalUrl, error == nil {
                // Success
                do {
                    try FileManager.default.copyItem(at: tempLocalUrl, to: destinationFileUrl)
                    result.succeed(destinationFileUrl as NSURL) //got error suggesting to add " as NSURL"
                } catch (let writeError) {
                    print("Error creating a file \(destinationFileUrl) : \(writeError)")
                    result.fail(writeError)
                }
                
            } else {
                print("Error took place while downloading a file. Error description: %@", error?.localizedDescription ?? String()); 
                result.fail(error!) 
            }
        }
        
        task.resume()
        
        return result.future //it expects NSURL now so I changed it to Promise<NSURL>
        
    }

Nonetheless, the same ambiguity error still pops up.

**Comment by vittoriom** [comment] 2017-06-15 17:07
All right, I just tried it locally and adding this:

```swift
extension NSURL: ExpensiveObject {
  public var cost: Int {
    return (self as URL).cost
  }
}
```

it compiles 👍

**Comment by blurtime** [comment] 2017-06-15 18:05
Thank you sooo much!! You cannot believe how grateful I am for your help and patience! If you want me to post all I have now for others, let me know. Keep up the awesome work!

**Comment by vittoriom** [comment] 2017-06-15 19:16
No problem! Feel free to post some snippets of code that could be useful for other people!

I'll close this issue in the mean time 👍

**Closed by vittoriom** 2017-06-15 19:16 UTC
Labels: feature, nice to have

**Comment by blurtime** [comment] 2017-06-15 19:39
Ok, I crowed to soon, another problem came across: I will describe the situation to make it as quick as possible.

The first time I load some video (a video that has never been downloaded by the custom fetcher) with the get function I get a link... This link looks now like this `file:///Users/myname/Library/Developer/CoreSimulator/Devices/9C74B031-9C62-4100-8FEB-8EC4CE2CA9BA/data/Containers/Data/Application/1D0991EC-7FA7-41DA-8481-0CFD0601742E/Documents/testvideo4.mov` because the file's name was `testvideo4.mov`. In addition to that I get the following logs by Carlos: 

    [Carlos][Debug]: Setting a value for the key https://blurtime.com/images/testvideo4.mov on the memory cache Carlos.MemoryCacheLevel<Foundation.URL, __ObjC.NSURL>
    [Carlos][Debug]: Setting a value for the key https://blurtime.com/images/testvideo4.mov on the disk cache Carlos.DiskCacheLevel<Foundation.URL, __ObjC.NSURL>

And although this file can be found under the URL I named above it is not playing the file (I am using `fileURLWithPath`) (this may only be secondarily important to you, but I'm not sure if it may be linked to the actual problem):

    let videosCache = videoCache.cache
        
    videosCache.get(URL(string: self.video!)!)
            .onSuccess { videoFile in
                
                print(videoFile)
                
                let videoURL = NSURL(fileURLWithPath: String(describing: videoFile))
                
                //player's video
                if self.player == nil {
                    
                    let playerItemToBePlayed = AVPlayerItem(url: videoURL as URL)
                    
                    self.player = AVPlayer(playerItem: playerItemToBePlayed)
                    
                    //add sub-layer
                    let playerLayer = AVPlayerLayer(player: self.player)
                    playerLayer.frame = self.view.frame
                    self.controlsContainerView.layer.insertSublayer(playerLayer, at: 0)
                    
                }
            }

But as if this weren't strange enough the following thing happens:

Whenever I run the project, the URL changes in a certain pattern, namely exactly one folder changes its name: The folder previously named `1D0991EC-7FA7-41DA-8481-0CFD0601742E` somehow changes (or renames(?)) itself to `28CCF7AD-A157-4542-9D9B-21181C8F3826`, the files in the folder (i.a. `testvideo4.mov`) remain. Finally and on top of all that, the printed `videoFile` is still the same one as when the video was loaded initially (in the first run). If I run it another time, the xeact same thing happens.

My fetcher is still the same as previously and my struct for the cache still looks like this:

    public struct videoCache {
        //create cache for videos
        static let cache = MemoryCacheLevel()
            .compose(DiskCacheLevel<URL, NSURL>())
            .compose(CustomFetcher())
    }

    extension NSURL: ExpensiveObject {
        public var cost: Int {
            return (self as URL).cost
        }
    }

**Comment by vittoriom** [comment] 2017-06-16 06:47
Hi, 
for the second issue you described, it might be related to how the iOS simulator works. Have you tried running the app without re-installing it from Xcode? Or have you tried running it on a device? 
Another option would be to only save the relative path from the `/Documents` folder, then it wouldn't matter if the app is re-installed and the container path changes.
